#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Oct 28, 2018 01:29:35 AM EDT  platform: Windows NT

import sys
from tkinter import *


try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

import hospitaldb1_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Welcome(root)
    hospitaldb1_support.init(root, top)
    root.mainloop()


w = None


def create_Welcome(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    top = Welcome(w)
    hospitaldb1_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Welcome():
    global w
    w.destroy()
    w = None


class Welcome:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#d9d9d9'  # X11 color: 'gray85'

        top.geometry("1030x1069+758+127")
        top.title("Welcome to our Hospital Management System")
        top.configure(background="#d9d9d9")

        self.NewPatientButton = tk.Button(top)
        self.NewPatientButton.place(relx=0.282, rely=0.281, height=104
                                    , width=382)
        self.NewPatientButton.configure(activebackground="#d9d9d9")
        self.NewPatientButton.configure(activeforeground="#000000")
        self.NewPatientButton.configure(background="#d9d9d9")
        self.NewPatientButton.configure(disabledforeground="#a3a3a3")
        self.NewPatientButton.configure(foreground="#000000")
        self.NewPatientButton.configure(highlightbackground="#d9d9d9")
        self.NewPatientButton.configure(highlightcolor="black")
        self.NewPatientButton.configure(pady="0")
        self.NewPatientButton.configure(text='''New Patient''')
        self.NewPatientButton.configure(width=382)

        self.AdministratorButton = tk.Button(top)
        self.AdministratorButton.place(relx=0.282, rely=0.449, height=114
                                       , width=392)
        self.AdministratorButton.configure(activebackground="#d9d9d9")
        self.AdministratorButton.configure(activeforeground="#000000")
        self.AdministratorButton.configure(background="#d9d9d9")
        self.AdministratorButton.configure(disabledforeground="#a3a3a3")
        self.AdministratorButton.configure(foreground="#000000")
        self.AdministratorButton.configure(highlightbackground="#d9d9d9")
        self.AdministratorButton.configure(highlightcolor="black")
        self.AdministratorButton.configure(pady="0")
        self.AdministratorButton.configure(text='''Administrator''')
        self.AdministratorButton.configure(width=392)


if __name__ == '__main__':
    vp_start_gui()
